# Generated by Django 5.2.8 on 2025-11-18 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_points', models.PositiveIntegerField(default=0, verbose_name='Puntos Totales Acumulados')),
                ('games_completed', models.PositiveSmallIntegerField(default=0, verbose_name='Juegos Completados')),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Puntuación de Jugador',
                'verbose_name_plural': 'Puntuaciones de Jugadores',
                'ordering': ['-total_points', 'last_updated'],
            },
        ),
        migrations.CreateModel(
            name='ScoreEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('QUESTION_CORRECT', 'Respuesta Correcta'), ('BONUS_LOCATION', 'Casilla de Bonificación'), ('PENALTY_LOCATION', 'Casilla de Penalización'), ('GAME_COMPLETED', 'Juego Completado'), ('ACHIEVEMENT', 'Logro / Medalla')], max_length=30, verbose_name='Tipo de Evento')),
                ('points_awarded', models.IntegerField(verbose_name='Puntos otorgados/restados')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Evento de Puntuación',
                'verbose_name_plural': 'Eventos de Puntuación',
                'ordering': ['-timestamp'],
            },
        ),
    ]
