# Generated by Django 5.2.8 on 2025-11-18 20:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gameplay', '0002_initial'),
        ('quizzes', '0001_initial'),
        ('ranking', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='playerscore',
            name='player',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='total_score', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='scoreevent',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='scoreevent',
            name='related_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gameplay.boardlocation'),
        ),
        migrations.AddField(
            model_name='scoreevent',
            name='related_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quizzes.question'),
        ),
    ]
