# Generated by Django 5.2.8 on 2025-11-18 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Texto de la Pregunta')),
                ('points', models.PositiveSmallIntegerField(default=10, verbose_name='Puntos por respuesta correcta')),
                ('theme', models.CharField(choices=[('NEGRITOS', 'Negritos de Huánuco'), ('INCAS', 'Cultura Inca'), ('HUANUCO_GENERAL', 'Historia General de Huánuco'), ('PERU_GENERAL', 'Patrimonio General del Perú')], default='NEGRITOS', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Pregunta de Trivia',
                'verbose_name_plural': 'Preguntas de Trivia',
            },
        ),
        migrations.CreateModel(
            name='TriviaFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título del Dato Curioso')),
                ('content', models.TextField(verbose_name='Contenido (Sabías que...)')),
                ('theme', models.CharField(choices=[('NEGRITOS', 'Negritos de Huánuco'), ('INCAS', 'Cultura Inca'), ('HUANUCO_GENERAL', 'Historia General de Huánuco'), ('PERU_GENERAL', 'Patrimonio General del Perú')], default='NEGRITOS', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Dato Curioso',
                'verbose_name_plural': 'Datos Curiosos',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300, verbose_name='Texto de la Respuesta')),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quizzes.question')),
            ],
            options={
                'verbose_name': 'Respuesta',
                'verbose_name_plural': 'Respuestas',
            },
        ),
    ]
