# Generated by Django 5.2.8 on 2025-11-18 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_id', models.PositiveSmallIntegerField(unique=True, verbose_name='ID de Posición')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre de la Casilla')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción de la Casilla')),
                ('type', models.CharField(choices=[('START', 'Inicio'), ('QUESTION', 'Casilla de Pregunta'), ('TRIVIA', 'Casilla de Sabías Que...'), ('BONUS', 'Casilla de Bonificación'), ('PENALTY', 'Casilla de Penalización'), ('END', 'Fin del Recorrido')], default='TRIVIA', max_length=20)),
                ('related_question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quizzes.question', verbose_name='Pregunta asociada (si aplica)')),
                ('related_trivia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quizzes.triviafact', verbose_name='Dato Curioso asociado (si aplica)')),
            ],
            options={
                'verbose_name': 'Casilla del Tablero',
                'verbose_name_plural': 'Casillas del Tablero',
                'ordering': ['location_id'],
            },
        ),
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_dice_roll', models.PositiveSmallIntegerField(default=0)),
                ('is_completed', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('current_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions_at_location', to='gameplay.boardlocation')),
            ],
            options={
                'verbose_name': 'Sesión de Juego',
                'verbose_name_plural': 'Sesiones de Juego',
            },
        ),
    ]
