# Generated by Django 5.2.8 on 2025-11-20 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nombre del Avatar')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción del Avatar')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='URL de la Imagen')),
            ],
            options={
                'verbose_name': 'Avatar',
                'verbose_name_plural': 'Avatares',
            },
        ),
        migrations.AddField(
            model_name='gamesession',
            name='avatar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gameplay.avatar', verbose_name='Avatar Seleccionado'),
        ),
    ]
